Controllers/API/CustomersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vidly.Data;
using vidly.Dtos;
using vidly.Models;

namespace vidly.Controllers.API
{
  [Route("/api/[controller]")]
  public class CustomersController : Controller
  {

    private readonly ApplicationDbContext context;
    private readonly IMapper mapper;

    public CustomersController(ApplicationDbContext context, IMapper mapper)
    {
      this.mapper = mapper;
      this.context = context;
    }


    [HttpGet]
    public async Task<IEnumerable<CustomerDto>> GetCustomers()
    {
      var customers = await context.Customers
        .Include(m => m.MembershipType)
        .ToListAsync();

      return mapper.Map<IEnumerable<Customer>, IEnumerable<CustomerDto>>(customers);
    }

    [Route("{id:int}")]
    [HttpGet]
    public async Task<IActionResult> GetCustomer(int id)
    {
      // var customer = await context.Customers
      //     .SingleOrDefault(c => c.Id == id);

      var customer = await context.Customers
          .Include(m => m.MembershipType)
          .SingleOrDefaultAsync(c => c.Id == id);


      if (customer == null)
        return NotFound();

      
      return Ok(mapper.Map<Customer, CustomerDto>(customer));
    }


    [HttpPost]
    public async Task<IActionResult> NewCustomer([FromBody] CustomerDto customerDto)
    {
      if (!ModelState.IsValid)
        return BadRequest();

      var customer = mapper.Map<CustomerDto, Customer>(customerDto);

      context.Customers.Add(customer);
      context.SaveChanges();

      customerDto.Id = customer.Id;
      return Ok(customerDto);
    }

    [Route("{id:int}")]
    [HttpPut]
    public async Task<IActionResult> UpdateCustomer(int id, [FromBody] CustomerDto customerDto)
    {
      if (!ModelState.IsValid)
        return BadRequest();


      var customerInDb = await context.Customers
          .SingleOrDefaultAsync(c => c.Id == id);

      if (customerInDb == null)
        return NotFound();


      mapper.Map<CustomerDto, Customer>(customerDto, customerInDb);

      context.SaveChanges();

      return Ok(customerDto);
    }

    [Route("{id:int}")]
    [HttpDelete]
    public async Task<IActionResult> DeleteCustomer(int id)
    {
      var customer = await context.Customers
          .SingleOrDefaultAsync(c => c.Id == id);

      if (customer == null)
        return NotFound();

      context.Remove(customer);
      context.SaveChanges();
      return Ok();
    }

  }
}

Controllers/API/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vidly.Data;
using vidly.Dtos;
using vidly.Models;

namespace vidly.Controllers.API
{
    
  [Route("/api/[controller]")]
  public class MoviesController : Controller
  {

    private readonly ApplicationDbContext context;
    private readonly IMapper mapper;

    public MoviesController(ApplicationDbContext context, IMapper mapper)
    {
      this.mapper = mapper;
      this.context = context;
    }


    [HttpGet]
    public async Task<IEnumerable<MovieDto>> GetMovies()
    {
      var movies = await context.Movies.ToListAsync();

      return mapper.Map<IEnumerable<Movie>, IEnumerable<MovieDto>>(movies);
    }

    [Route("{id:int}")]
    [HttpGet]
    public async Task<IActionResult> GetMovie(int id)
    {
      // var customer = await context.Customers
      //     .SingleOrDefault(c => c.Id == id);

      var movie = await context.Movies
          .SingleOrDefaultAsync(m => m.Id == id);


      if (movie == null)
        return NotFound();

      
      return Ok(mapper.Map<Movie, MovieDto>(movie));
    }


    [HttpPost]
    public async Task<IActionResult> NewMovie([FromBody] MovieDto movieDto)
    {
      if (!ModelState.IsValid)
        return BadRequest();

      var movie = mapper.Map<MovieDto, Movie>(movieDto);
      movie.Added = DateTime.Now;
      context.Movies.Add(movie);
      context.SaveChanges();

      movieDto.Added = movie.Added;
      movieDto.Id = movie.Id;
      return Ok(movieDto);
    }

    [Route("{id:int}")]
    [HttpPut]
    public async Task<IActionResult> UpdateMovie(int id, [FromBody] MovieDto movieDto)
    {
      if (!ModelState.IsValid)
        return BadRequest();

      var movieInDb = await context.Movies
        .SingleOrDefaultAsync(m => m.Id == id);


      if (movieInDb == null)
        return NotFound();


      mapper.Map<MovieDto, Movie>(movieDto, movieInDb);

      context.SaveChanges();

      mapper.Map<Movie, MovieDto>(movieInDb, movieDto);

      return Ok(movieDto);
    }

    [Route("{id:int}")]
    [HttpDelete]
    public async Task<IActionResult> DeleteMovie(int id)
    {
      var movie = await context.Movies
        .SingleOrDefaultAsync(m => m.Id == id);

      if (movie == null)
        return NotFound();

      context.Remove(movie);
      context.SaveChanges();
      return Ok();
    }

  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>

    <!--<environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.min.css" />
        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-lumen.min.css"

              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            
        
        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.css"/>>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>-->
    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-lumen.min.css"

              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            
        
        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.css"/>>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>


</head>
<body>
   @Html.Partial("_NavBar")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
        <script src="~/lib/datatables/media/js/jquery.dataTables.js"></script>
        <script src="~/lib/datatables/media/js/dataTables.bootstrap.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
 <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Customers" asp-action="Index" class="navbar-brand">Vidly</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
    </div>